name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and Push the Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/enra-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/enra-app:latest

      # Step 4: Deploy to Digital Ocean Droplet
      - name: Deploy to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ""
          target: "/root"

      - name: Restart Docker Container on Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/enra-app:latest
            docker stop enra-app-container || true
            docker rm enra-app-container || true
            docker run -d --name react-app-container -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/enra-app:latest
